---
- name: Create Jenkins directory
  file: path=/home/jenkins/cli state=directory

- name: Copy install jenkins plugins shell script
  template: src=install-jenkins-plugin.sh.j2 dest=/home/jenkins/install-jenkins-plugins.sh

- name: Install jenkins plugins
  shell: bash /home/jenkins/install-jenkins-plugins.sh {{item}}
  with_items:
  - ansible
  - ant
  - antisamy-markup-formatter
  - aws-java-sdk
  - categorized-view
  - conditional-buildstep
  - copyartifact
  - credentials
  - external-monitor-job
  - git
  - git-client
  - github
  - htmlpublisher
  - icon-shim
  - jackson2-api
  - javadoc
  - jobConfigHistory
  - junit
  - ldap
  - mailer
  - matrix-project
  - maven-plugin
  - multiple-scms
  - nexus-artifact-uploader
  - pam-auth
  - parameterized-trigger
  - performance
  - pipeline-utility-steps
  - rebuild
  - run-condition
  - s3
  - scm-api
  - script-security
  - ssh-credentials
  - structs
  - thinBackup
  - token-macro
  - windows-slaves
  - workflow-step-api
  - workflow-aggregator
  - matrix-auth
  - extended-choice-parameter 

- name: Stop Jenkins
  service: name=jenkins state=stopped

- name: Disable Security in Jenkins Config
  shell: sed -i 's#<useSecurity>true</useSecurity>#<useSecurity>false</useSecurity>#g' /var/lib/jenkins/config.xml

- name: Start Jenkins
  service: name=jenkins state=started

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  retries: 60
  delay: 5
  until: >
    'status' in jenkins_service_status and jenkins_service_status['status'] == 200

- name: Install specific version of Nexus Jenkins Plugin
  jenkins_plugin:
    name: nexus-jenkins-plugin
    version: "3.5.20190425-152158.c63841b"
