---
- name: Adding Jenkins user
  user: name=jenkins groups=sudo,shadow shell=/bin/bash append=yes generate_ssh_key=yes ssh_key_file=.ssh/id_rsa

- name: Adding Jenkins user to sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^%jenkins' line='%jenkins ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Add the Jenkins APT repository key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add the Jenkins APT repository
  apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/" state=present

- name: Configure Jenkins
  template: src=jenkins.j2 dest=/etc/default/jenkins

- name: Create Init Folder for Groovy to disable Jenkins setup wizard
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory

- name: Disable Initial Admin Setup
  copy:
    src: /home/aws/liatrio/basic-security.groovy
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy

- name: Restart Jenkins 
  service:
    name: jenkins
    state: restarted
